#!/usr/bin/env node
/**
 * Builds the six Grizzly Energy can labels from src/data/grizzly.json.
 *
 *   node scripts/build-labels.mjs            # all flavors
 *   node scripts/build-labels.mjs peach      # one flavor
 *
 * Output (per flavor, same 2048×1603 UV layout as before):
 *   public/textures/grizzly/<slug>.webp          flat albedo (no baked shading)
 *   public/textures/grizzly/<slug>-surface.png   G = roughness, B = metalness (glTF convention)
 *   public/textures/grizzly/<slug>-front.png     front panel only, for review
 * plus src/styles/flavor-tokens.css (one accent token per flavor).
 *
 * Front panel: cropped from the flavor's flat artwork when data.front is set
 * (misspelled small text covered by patches with real text); otherwise a
 * temporary type-only front is drawn until flat artwork is supplied.
 * Side panels are always drawn in code from the data file.
 */
import { chromium } from 'playwright';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const data = JSON.parse(await readFile(resolve(root, 'src/data/grizzly.json'), 'utf8'));
const only = process.argv[2];
const outDir = resolve(root, 'public/textures/grizzly');
await mkdir(outDir, { recursive: true });

// ---------- flavor tokens (single source: grizzly.json) ----------
const tokenLines = [
  '/* GENERATED by scripts/build-labels.mjs from src/data/grizzly.json — do not edit by hand. */',
  ':root {',
  ...data.flavors.flatMap((f) => [
    `  --color-flavor-${f.accentToken}: ${f.accent};`,
    `  --color-flavor-${f.accentToken}-deep: ${f.accentDeep};`,
  ]),
  `  --gradient-flavor-range: linear-gradient(90deg, ${data.flavors
    .map((f, i) => `var(--color-flavor-${f.accentToken}) ${Math.round((i / (data.flavors.length - 1)) * 100)}%`)
    .join(', ')});`,
  '}',
  '',
  ...data.flavors.flatMap((f, i) => {
    const next = data.flavors[(i + 1) % data.flavors.length];
    return [
      `:root[data-flavor='${f.slug}'], [data-accent='${f.accentToken}'] {`,
      `  --color-accent: var(--color-flavor-${f.accentToken});`,
      `  --color-accent-deep: var(--color-flavor-${f.accentToken}-deep);`,
      `  --color-accent-next: var(--color-flavor-${next.accentToken});`,
      '}',
    ];
  }),
  '',
];
await writeFile(resolve(root, 'src/styles/flavor-tokens.css'), tokenLines.join('\n'));

// ---------- render labels in headless Chromium (Canvas 2D) ----------
const browser = await chromium.launch();
const page = await browser.newPage();
await page.setContent(`<!doctype html><html><head>
<link href="https://fonts.googleapis.com/css2?family=Geist:wght@300;400;500;700&family=Libre+Franklin:ital,wght@1,700;1,900&display=block" rel="stylesheet">
</head><body></body></html>`);
await page.evaluate(async () => {
  await Promise.all([
    "italic 900 40px 'Libre Franklin'", "italic 700 40px 'Libre Franklin'",
    "300 20px 'Geist'", "400 20px 'Geist'", "500 20px 'Geist'", "700 20px 'Geist'",
  ].map((font) => document.fonts.load(font)));
});

for (const flavor of data.flavors) {
  if (only && flavor.slug !== only) continue;
  let frontSrc = null;
  if (flavor.front) {
    const bytes = await readFile(resolve(root, flavor.front.src));
    frontSrc = `data:image/jpeg;base64,${bytes.toString('base64')}`;
  }
  const result = await page.evaluate(drawLabel, { data, flavor, frontSrc });
  const decode = (url) => Buffer.from(url.split(',')[1], 'base64');
  await writeFile(resolve(outDir, `${flavor.slug}.webp`), decode(result.albedo));
  await writeFile(resolve(outDir, `${flavor.slug}-surface.png`), decode(result.surface));
  await writeFile(resolve(outDir, `${flavor.slug}-front.png`), decode(result.front));
  await writeFile(resolve(outDir, `${flavor.slug}-normal.png`), decode(result.normal));
  console.log(`✓ ${flavor.slug}${flavor.front ? '' : '  (temporary type-only front: awaiting flat artwork)'}`);
}

await browser.close();

/**
 * Runs in the browser. Returns data URLs for albedo, surface and front preview.
 * Everything is flat colour: the 3D scene adds light, shading and curvature.
 */
async function drawLabel({ data, flavor, frontSrc }) {
  // Draw in the 2048-wide layout space, rasterise at drawScale (4096 px) for sharp close-ups.
  const SCALE = data.label.drawScale ?? 1;
  const W = data.label.size[0] / SCALE;
  const H = data.label.size[1] / SCALE;
  const P = data.label.panels;
  const accent = flavor.accent;
  const BLACK = '#0b0b0d';
  const WHITE = '#f2f4f7';
  const MUTED = '#a9adb5';
  const SILVER = '#d7dbe1';
  const isTodo = (value) => typeof value === 'string' && value.startsWith('TODO');
  const shown = (value) => (isTodo(value) ? 'TBC' : value);

  const canvas = document.createElement('canvas');
  canvas.width = W * SCALE;
  canvas.height = H * SCALE;
  const ctx = canvas.getContext('2d');
  ctx.scale(SCALE, SCALE);
  ctx.imageSmoothingQuality = 'high';
  // Surface map: G = roughness, B = metalness (R/A unused). Satin black print by default.
  const surface = document.createElement('canvas');
  surface.width = W * SCALE;
  surface.height = H * SCALE;
  const sctx = surface.getContext('2d');
  sctx.scale(SCALE, SCALE);
  const BODY_SURFACE = 'rgb(255,110,90)';
  const SILVER_SURFACE = 'rgb(255,64,255)';
  sctx.fillStyle = BODY_SURFACE;
  sctx.fillRect(0, 0, W, H);

  ctx.fillStyle = BLACK;
  ctx.fillRect(0, 0, W, H);

  const px = (u) => Math.round(u * W);
  const py = (v) => Math.round((1 - v) * H); // v = 1 at the top of the texture

  // ---------- helpers ----------
  const text = (str, x, y, font, color, align = 'left', spacing = 0) => {
    ctx.font = font;
    ctx.fillStyle = color;
    ctx.textAlign = align;
    ctx.textBaseline = 'alphabetic';
    if ('letterSpacing' in ctx) ctx.letterSpacing = `${spacing}px`;
    ctx.fillText(str, x, y);
    if ('letterSpacing' in ctx) ctx.letterSpacing = '0px';
  };
  const wrap = (str, x, y, maxWidth, font, color, lineHeight) => {
    ctx.font = font;
    const words = str.split(' ');
    let line = '';
    let cy = y;
    for (const word of words) {
      const test = line ? `${line} ${word}` : word;
      if (ctx.measureText(test).width > maxWidth && line) {
        text(line, x, cy, font, color);
        line = word;
        cy += lineHeight;
      } else {
        line = test;
      }
    }
    if (line) text(line, x, cy, font, color);
    return cy + lineHeight;
  };
  const silverMark = (x, y, w, h) => {
    sctx.fillStyle = SILVER_SURFACE;
    sctx.fillRect(x, y, w, h);
  };
  const hexagon = (cx, cy, r, stroke, width = 4) => {
    ctx.beginPath();
    for (let i = 0; i < 6; i++) {
      const a = Math.PI / 6 + (i * Math.PI) / 3;
      ctx[i ? 'lineTo' : 'moveTo'](cx + r * Math.cos(a), cy + r * Math.sin(a));
    }
    ctx.closePath();
    ctx.strokeStyle = stroke;
    ctx.lineWidth = width;
    ctx.stroke();
  };
  const icon = (type, cx, cy, s, color) => {
    ctx.save();
    ctx.translate(cx, cy);
    ctx.scale(s / 24, s / 24);
    ctx.fillStyle = color;
    ctx.strokeStyle = color;
    ctx.lineWidth = 2;
    ctx.lineJoin = 'round';
    if (type === 'caffeine') {
      ctx.beginPath();
      ctx.moveTo(2, -11); ctx.lineTo(-7, 2); ctx.lineTo(-1, 2); ctx.lineTo(-3, 11); ctx.lineTo(7, -3); ctx.lineTo(1, -3); ctx.closePath();
      ctx.fill();
    } else if (type === 'electrolytes') {
      ctx.beginPath();
      ctx.moveTo(0, -11);
      ctx.bezierCurveTo(6, -3, 8, 1, 8, 4); ctx.arc(0, 4, 8, 0, Math.PI); ctx.bezierCurveTo(-8, 1, -6, -3, 0, -11);
      ctx.fill();
    } else if (type === 'vitamins') {
      ctx.font = "italic 900 24px 'Libre Franklin'";
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText('B', 0, 1);
    } else if (type === 'zamzam') {
      ctx.beginPath();
      ctx.moveTo(0, -11);
      ctx.bezierCurveTo(6, -3, 8, 1, 8, 4); ctx.arc(0, 4, 8, 0, Math.PI); ctx.bezierCurveTo(-8, 1, -6, -3, 0, -11);
      ctx.stroke();
      ctx.beginPath();
      ctx.moveTo(-6, 5); ctx.quadraticCurveTo(-3, 2, 0, 5); ctx.quadraticCurveTo(3, 8, 6, 5);
      ctx.stroke();
    } else if (type === 'leaf') {
      ctx.beginPath();
      ctx.moveTo(-8, 8); ctx.bezierCurveTo(-8, -6, 2, -10, 9, -9); ctx.bezierCurveTo(9, 0, 4, 8, -8, 8); ctx.fill();
    } else if (type === 'flask') {
      ctx.beginPath();
      ctx.moveTo(-3, -10); ctx.lineTo(3, -10); ctx.moveTo(-2, -10); ctx.lineTo(-2, -3); ctx.lineTo(-8, 9); ctx.lineTo(8, 9); ctx.lineTo(2, -3); ctx.lineTo(2, -10);
      ctx.stroke();
    } else if (type === 'recycle') {
      ctx.beginPath();
      ctx.arc(0, 0, 8, Math.PI * 0.1, Math.PI * 1.7); ctx.stroke();
      ctx.beginPath(); ctx.moveTo(6, -9); ctx.lineTo(9, -4); ctx.lineTo(3, -4); ctx.closePath(); ctx.fill();
    }
    ctx.restore();
  };
  const flagPK = (x, y, w) => {
    const h = w * (2 / 3);
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(x, y, w * 0.25, h);
    ctx.fillStyle = '#01411c';
    ctx.fillRect(x + w * 0.25, y, w * 0.75, h);
    const cx = x + w * 0.625;
    const cy = y + h / 2;
    ctx.fillStyle = '#ffffff';
    ctx.beginPath(); ctx.arc(cx, cy, h * 0.3, 0, Math.PI * 2); ctx.fill();
    ctx.fillStyle = '#01411c';
    ctx.beginPath(); ctx.arc(cx + h * 0.08, cy - h * 0.06, h * 0.26, 0, Math.PI * 2); ctx.fill();
    ctx.fillStyle = '#ffffff';
    ctx.beginPath();
    for (let i = 0; i < 10; i++) {
      const r = i % 2 ? h * 0.04 : h * 0.1;
      const a = -Math.PI / 2 + (i * Math.PI) / 5;
      ctx[i ? 'lineTo' : 'moveTo'](cx + h * 0.18 + r * Math.cos(a), cy - h * 0.12 + r * Math.sin(a));
    }
    ctx.fill();
  };
  const wordmark = (x, y, size, align = 'left') => {
    ctx.font = `italic 900 ${size}px 'Libre Franklin'`;
    const w1 = ctx.measureText(data.brand.wordmark[0]).width;
    const ox = align === 'center' ? x - w1 / 2 : x;
    text(data.brand.wordmark[0], ox, y, ctx.font, SILVER, 'left', -size * 0.02);
    silverMark(ox - 4, y - size * 0.8, w1 + 8, size * 0.88);
    ctx.font = `italic 900 ${size * 0.72}px 'Libre Franklin'`;
    const w2 = ctx.measureText(data.brand.wordmark[1]).width;
    text(data.brand.wordmark[1], align === 'center' ? x - w2 / 2 + size * 0.1 : x + size * 0.2, y + size * 0.72, ctx.font, accent, 'left', -size * 0.01);
  };

  // ---------- LEFT PANEL: brand, ingredients, nutrition ----------
  {
    const x = px(P.left[0]) + 20;
    const w = px(P.left[1]) - px(P.left[0]) - 40;
    wordmark(x, 150, 104);
    text(data.brand.tagline.toUpperCase(), x + 6, 278, "500 22px 'Geist'", WHITE, 'left', 7);
    // origin + flag (the claim lives on the right panel)
    const cx = x + w - 96;
    text(data.brand.origin.split(' ').slice(0, 2).join(' ').toUpperCase(), cx + 36, 82, "700 16px 'Geist'", WHITE, 'center', 1);
    text(data.brand.origin.split(' ').slice(2).join(' ').toUpperCase(), cx + 36, 102, "700 16px 'Geist'", WHITE, 'center', 1);
    flagPK(cx, 116, 72);

    let y = wrap(data.brand.intro, x, 346, w, "400 22px 'Geist'", WHITE, 32) + 18;
    text('INGREDIENTS', x, y, "italic 900 24px 'Libre Franklin'", accent, 'left', 0.5);
    y = wrap(isTodo(flavor.ingredients) ? data.label.neutral.ingredients : flavor.ingredients, x, y + 34, w, "400 20px 'Geist'", WHITE, 28) + 14;

    // caffeine box
    ctx.strokeStyle = accent;
    ctx.lineWidth = 3;
    ctx.strokeRect(x, y, w, 76);
    icon('caffeine', x + 38, y + 38, 40, accent);
    text('CAFFEINE CONTENT', x + 76, y + 33, "italic 900 22px 'Libre Franklin'", WHITE);
    text(isTodo(data.unconfirmed.caffeine) ? data.label.neutral.caffeine : data.unconfirmed.caffeine, x + 76, y + 62, "400 20px 'Geist'", MUTED);
    y += 112;
    y = wrap(data.brand.warning, x, y, w, "400 20px 'Geist'", WHITE, 28) + 10;

    // nutrition table
    // Unconfirmed rows are left off the printed label until supplied.
    const rows = data.nutrition.rows.filter(([, value]) => !isTodo(value));
    const rowH = 31;
    const boxH = 70 + rows.length * rowH;
    ctx.strokeStyle = accent;
    ctx.lineWidth = 3;
    ctx.strokeRect(x, y, w, boxH);
    text('NUTRITION FACTS', x + 18, y + 38, "italic 900 26px 'Libre Franklin'", accent);
    text(data.nutrition.serving, x + w - 18, y + 38, "400 18px 'Geist'", MUTED, 'right');
    let ry = y + 58;
    for (const [label, value] of rows) {
      ctx.fillStyle = '#2a2d33';
      ctx.fillRect(x + 18, ry, w - 36, 1);
      const indent = label.startsWith('of which') ? 22 : 0;
      text(label, x + 18 + indent, ry + 23, "400 19px 'Geist'", WHITE);
      text(value, x + w - 18, ry + 23, "500 19px 'Geist'", WHITE, 'right');
      ry += rowH;
    }
    y += boxH + 30;
    y = wrap(data.brand.storage, x, y, w, "400 18px 'Geist'", MUTED, 26) + 16;
    text(data.brand.company.name.toUpperCase(), x, y, "700 18px 'Geist'", WHITE, 'left', 0.5);
    if (isTodo(data.brand.company.address)) {
      text(data.brand.company.website, x, y + 26, "500 18px 'Geist'", WHITE);
    } else {
      text(data.brand.company.address, x, y + 26, "400 18px 'Geist'", MUTED);
      text(data.brand.company.website, x, y + 52, "500 18px 'Geist'", WHITE);
    }
  }

  // ---------- RIGHT PANEL: claim, the four benefits, badges ----------
  {
    const x = px(P.right[0]) + 10;
    const w = px(P.right[1]) - px(P.right[0]) - 20;
    text(data.brand.claim[0].toUpperCase(), x, 120, "italic 900 46px 'Libre Franklin'", WHITE);
    text(data.brand.claim[1].toUpperCase(), x, 172, "italic 900 46px 'Libre Franklin'", WHITE);
    ctx.fillStyle = accent;
    ctx.fillRect(x, 196, w * 0.82, 3);

    data.benefits.forEach((benefit, i) => {
      const [, v0, , v1] = data.label.benefitBlocks[i];
      const top = py(v1);
      const bottom = py(v0);
      const mid = (top + bottom) / 2;
      hexagon(x + 46, mid, 42, accent, 4);
      icon(benefit.icon, x + 46, mid, 40, accent);
      const tx = x + 112;
      text(benefit.title.toUpperCase(), tx, mid - 34, "italic 900 28px 'Libre Franklin'", accent);
      text(benefit.spec.toUpperCase(), tx, mid - 6, "500 17px 'Geist'", WHITE, 'left', 0.5);
      wrap(benefit.labelDetail, tx, mid + 22, w - 116, "400 18px 'Geist'", WHITE, 24);
      if (i < data.benefits.length - 1) {
        ctx.fillStyle = '#2a2d33';
        ctx.fillRect(tx, bottom + 6, w - 116, 2);
      }
    });

    // badges row
    const by = py(data.label.benefitBlocks[3][1]) + 90;
    const badges = [['leaf', data.badges[0]], ['flask', data.badges[1]], ['flask', data.badges[2]]];
    badges.forEach(([type, label], i) => {
      const cx = x + 70 + i * ((w - 40) / 3);
      ctx.strokeStyle = WHITE;
      ctx.lineWidth = 3;
      ctx.beginPath(); ctx.arc(cx, by, 36, 0, Math.PI * 2); ctx.stroke();
      icon(type, cx, by, 34, WHITE);
      const words = label.toUpperCase().split(' ');
      text(words.slice(0, 2).join(' '), cx, by + 66, "700 15px 'Geist'", WHITE, 'center');
      if (words.length > 2) text(words.slice(2).join(' '), cx, by + 86, "700 15px 'Geist'", WHITE, 'center');
    });

    // halal, recycle, barcode
    const hy = by + 200;
    ctx.strokeStyle = WHITE;
    ctx.lineWidth = 4;
    ctx.beginPath(); ctx.arc(x + 70, hy, 52, 0, Math.PI * 2); ctx.stroke();
    text('حلال', x + 70, hy + 2, "700 34px 'Geist'", WHITE, 'center');
    text('HALAL', x + 70, hy + 34, "700 16px 'Geist'", WHITE, 'center');
    text('HALAL CERTIFIED', x + 70, hy + 84, "700 16px 'Geist'", WHITE, 'center');
    if (!isTodo(data.unconfirmed.halalCertifier)) text(data.unconfirmed.halalCertifier, x + 70, hy + 106, "400 14px 'Geist'", MUTED, 'center');
    icon('recycle', x + 210, hy - 6, 50, WHITE);
    text('PLEASE', x + 210, hy + 50, "700 15px 'Geist'", WHITE, 'center');
    text('RECYCLE', x + 210, hy + 70, "700 15px 'Geist'", WHITE, 'center');
    // Barcode area stays blank until the EAN is supplied (see grizzly.json → unconfirmed.barcode).
    text(data.brand.volume.replace(' ', '').toUpperCase(), x + 290 + (w - 300) / 2, hy - 6, "italic 900 34px 'Libre Franklin'", WHITE, 'center');
    text(data.brand.productType.toUpperCase(), x + 290 + (w - 300) / 2, hy + 24, "500 16px 'Geist'", MUTED, 'center', 3);
  }

  // ---------- FRONT PANEL ----------
  const fx0 = px(P.front[0]);
  const fw = px(P.front[1]) - fx0;
  const front = document.createElement('canvas');
  if (frontSrc) {
    const img = new Image();
    img.src = frontSrc;
    await img.decode();
    const [sx, sy, sw, sh] = flavor.front.crop;
    const scale = fw / sw;
    const fh = Math.round(sh * scale);
    front.width = sw;
    front.height = sh;
    const f = front.getContext('2d');
    f.drawImage(img, sx, sy, sw, sh, 0, 0, sw, sh);
    // Cover misspelled small text with matching patches and real text.
    for (const patch of flavor.front.patches) {
      const [x, y, w, h] = patch.box;
      if (patch.fill === 'auto') {
        // Average the pixels just below and beside the patch (not above, where
        // name plates sit) so it blends into the artwork.
        const ring = [
          f.getImageData(x, y + h, w, 3).data,
          f.getImageData(Math.max(0, x - 3), y, 3, h).data,
          f.getImageData(x + w, y, 3, h).data,
        ];
        let r = 0, g = 0, b = 0, n = 0;
        for (const part of ring) for (let k = 0; k < part.length; k += 4) { r += part[k]; g += part[k + 1]; b += part[k + 2]; n += 1; }
        f.fillStyle = `rgb(${Math.round(r / n)}, ${Math.round(g / n)}, ${Math.round(b / n)})`;
      } else if (Array.isArray(patch.fill)) {
        const gradient = f.createLinearGradient(x, 0, x + w, 0);
        patch.fill.forEach((stop, i) => gradient.addColorStop(i / (patch.fill.length - 1), stop));
        f.fillStyle = gradient;
      } else {
        f.fillStyle = patch.fill;
      }
      f.fillRect(x, y, w, h);
      if (patch.border) {
        f.strokeStyle = patch.border;
        f.lineWidth = 1.5;
        f.beginPath();
        f.roundRect(x + 8, y + 10, w - 16, h - 20, (h - 20) / 2);
        f.stroke();
      }
      f.font = patch.font;
      f.fillStyle = patch.color;
      f.textAlign = 'center';
      f.textBaseline = 'middle';
      f.fillText(patch.text, x + w / 2, y + h / 2 + 1);
    }
    const fy = Math.round((H - fh) / 2);
    ctx.drawImage(front, 0, 0, sw, sh, fx0, fy, fw, fh);
    // Silver wordmark: mirror-like only where the artwork is light and neutral.
    const [mx, my, mw, mh] = flavor.front.silver;
    const sample = f.getImageData(mx, my, mw, mh).data;
    for (let j = 0; j < mh; j += 1) {
      for (let i = 0; i < mw; i += 1) {
        const k = (j * mw + i) * 4;
        const r = sample[k], g = sample[k + 1], b = sample[k + 2];
        const max = Math.max(r, g, b), min = Math.min(r, g, b);
        if (max > 150 && max - min < 28) {
          sctx.fillStyle = SILVER_SURFACE;
          sctx.fillRect(fx0 + (mx + i) * scale, fy + (my + j) * scale, Math.ceil(scale), Math.ceil(scale));
        }
      }
    }
  } else {
    // Temporary type-only front (awaiting flat artwork): same structure as the design.
    const cx = fx0 + fw / 2;
    ctx.fillStyle = accent;
    ctx.fillRect(fx0, 70, fw, 66);
    text((flavor.edition ?? flavor.name).toUpperCase(), cx, 116, "italic 900 34px 'Libre Franklin'", '#ffffff', 'center', 2);
    // Brand mountain motif (stand-in for the bear until flat artwork arrives).
    const peaks = [[-250, 520], [-150, 330], [-60, 430], [40, 250], [150, 410], [230, 340], [300, 520]];
    ctx.beginPath();
    peaks.forEach(([dx, y], i) => ctx[i ? 'lineTo' : 'moveTo'](cx + dx, y));
    ctx.lineJoin = 'round';
    ctx.lineWidth = 6;
    ctx.strokeStyle = accent;
    ctx.stroke();
    ctx.globalAlpha = 0.18;
    ctx.fillStyle = accent;
    ctx.fill();
    ctx.globalAlpha = 1;
    ctx.fillStyle = WHITE;
    [[-150, 330], [40, 250], [230, 340]].forEach(([dx, y]) => {
      ctx.beginPath();
      ctx.moveTo(cx + dx, y);
      ctx.lineTo(cx + dx - 34, y + 46);
      ctx.lineTo(cx + dx + 34, y + 46);
      ctx.closePath();
      ctx.fill();
    });
    wordmark(cx, 700, 150, 'center');
    text(data.brand.tagline.toUpperCase(), cx, 900, "italic 900 34px 'Libre Franklin'", WHITE, 'center', 3);
    ctx.fillStyle = accent;
    ctx.fillRect(fx0 + 90, 1010, fw - 180, 70);
    text(flavor.name.toUpperCase(), cx, 1058, "italic 900 40px 'Libre Franklin'", '#ffffff', 'center');
    text('NATURALLY FLAVORED', cx, 1112, "italic 400 20px 'Geist'", WHITE, 'center', 2);
    data.benefits.forEach((benefit, i) => {
      const bx = fx0 + 90 + i * ((fw - 180) / 3);
      hexagon(bx, 1210, 40, accent, 4);
      icon(benefit.icon, bx, 1210, 38, accent);
      text(benefit.lines[0].toUpperCase(), bx, 1282, "700 17px 'Geist'", WHITE, 'center');
      if (benefit.lines[1]) text(benefit.lines[1].toUpperCase(), bx, 1304, "400 15px 'Geist'", MUTED, 'center');
    });
    text('HALAL CERTIFIED', cx - 120, 1400, "700 20px 'Geist'", WHITE, 'center');
    text(data.brand.origin.toUpperCase(), cx + 130, 1400, "700 20px 'Geist'", WHITE, 'center');
    text(`${data.brand.volume.replace(' ', '')}  |  ${data.brand.productType.toUpperCase()}`, cx, 1490, "400 26px 'Geist'", WHITE, 'center', 3);
    front.width = fw;
    front.height = H;
    front.getContext('2d').drawImage(canvas, fx0, 0, fw, H, 0, 0, fw, H);
  }

  // Emboss normal map (half resolution): height = blurred silver mask, so the
  // brushed wordmark sits slightly raised. Flat elsewhere (128,128,255).
  const NW = Math.round(W);
  const NH = Math.round(H);
  const heightCanvas = document.createElement('canvas');
  heightCanvas.width = NW;
  heightCanvas.height = NH;
  const hctx = heightCanvas.getContext('2d');
  hctx.filter = 'blur(2px)';
  hctx.drawImage(surface, 0, 0, NW, NH);
  const heightData = hctx.getImageData(0, 0, NW, NH).data;
  const normal = document.createElement('canvas');
  normal.width = NW;
  normal.height = NH;
  const nctx = normal.getContext('2d');
  const out = nctx.createImageData(NW, NH);
  const h = (x, y) => heightData[((Math.min(NH - 1, Math.max(0, y)) * NW) + Math.min(NW - 1, Math.max(0, x))) * 4 + 2] / 255;
  const strength = 2.2;
  for (let y = 0; y < NH; y++) {
    for (let x = 0; x < NW; x++) {
      const dx = (h(x + 1, y) - h(x - 1, y)) * strength;
      const dy = (h(x, y + 1) - h(x, y - 1)) * strength;
      const len = Math.hypot(dx, dy, 1);
      const k = (y * NW + x) * 4;
      out.data[k] = Math.round((-dx / len * 0.5 + 0.5) * 255);
      out.data[k + 1] = Math.round((dy / len * 0.5 + 0.5) * 255);
      out.data[k + 2] = Math.round((1 / len * 0.5 + 0.5) * 255);
      out.data[k + 3] = 255;
    }
  }
  nctx.putImageData(out, 0, 0);

  return {
    normal: normal.toDataURL('image/png'),
    albedo: canvas.toDataURL('image/webp', 0.92),
    surface: surface.toDataURL('image/png'),
    front: front.toDataURL('image/png'),
  };
}
